### ISSUE TITLE
lib load warning

### ISSUE THREAD

**Issue by MontelukastNa** [boschresearch/sepMultiphaseFoam#2]
Hello, Anja Lippert & Tomislav Maric
Great work and Nice Paper.
`Nagel, L., Lippert, A., Tolle, T., Leonhardt, R., Zhang, H., Maric, T., 2023. Stabilizing the unstructured Volume-of-Fluid method for capillary flows in microstructures using artificial viscosity.`

I already adjusted  the TwoPhaseFlow library path and version at Make/option file's line 10 yet.
It complied successfully.
But, when I run the sepMultiphaseFoam case1~3 on OpenFOAM-v2212 + TwoPhaseFlow-of2206. A warning as below:

```
--> FOAM Warning : 
    From void* Foam::dlLibraryTable::openLibrary(const Foam::fileName&, bool)
    in file db/dynamicLibrary/dlLibraryTable/dlLibraryTable.C at line 188
    Could not load "libfvOptionArtificialViscousInterfaceForce.so"
/home/dyfluid/OpenFOAM/dyfluid-v2206/platforms/linux64GccDPInt32Opt/lib/libfvOptionArtificialViscousInterfaceForce.so: undefined symbol: _ZTIN4Foam2fv13cellSetOptionE
```

```
--> FOAM Warning : 
    From void* Foam::dlLibraryTable::openLibrary(const Foam::fileName&, bool)
    in file db/dynamicLibrary/dlLibraryTable/dlLibraryTable.C at line 188
    Could not load "libisoAdvection_wispCorr.so"
/home/dyfluid/OpenFOAM/dyfluid-v2206/platforms/linux64GccDPInt32Opt/lib/libisoAdvection_wispCorr.so: undefined symbol: _ZTIN4Foam16advectionSchemesE
```
**Does this warning mean that what I'm doing is wrong, or can it just be used as a negligible warning?** 
_This warning also appeared with OpenFOAM-v2112 + TwoPhaseFlow-of2112._

Thanks!

All Best,
Na

**Comment by Luise-Nagel** [comment]
Hi Na, 

thank you for your interest in our work!

The warning is definitely not negligible, the libraries seem to be compiled unsuccessfully or in an incompatible version.

From your description it seems like you're not doing anything wrong.
Surely you sourced the correct OpenFOAM version before running the cases? 
Could you please also attach the compilation output?
I'll investigate further and try to find the error.

  _* EDIT-  could you also specify in which application the error occurs? Probably it occurs when you are running blockMesh? Do the other applications, mostly interIsoFoam or interFlow, also produce this warning? If it only occurs in blockMesh and setAlphaField, then it might be neglegible after all.... but it's still weird._

Thank you & best regards
Luise

**Comment by Luise-Nagel** [comment]
Hello again Na,

I investigated further and found that the warning only occurs in the blockMesh and setAlphaField applications, not when running the actual solver. Since the libraries are only necessary for the solver, the simulations should run correctly regardless of the warning.

Nevertheless I will try to find a fix to stop the warning from occurring. 

Let me know if this works for you.

BTW - please note that I recently submitted a small fix (1 line) in the wisp correction, which has not been merged. If you intend to use the wisp correction, the fix is necessary to get reasonable results.

Thanks again & let me know if you have further questions.

**Comment by MontelukastNa** [comment]
Hello Luise-Nagel,
I appreciate your kind reply, thank you very much.❤

I checked the version of my OpenFOAM and TwoPhaseFlow again, it is OpenFOAM-v2212 + TwoPhaseFlow2206.
Before ./Allwmake,  the ~/OpenFOAM-v2212/etc/bashrc was sourced correctly.

As you mentioned, the libraries are only necessary for the solver, the simulations should run correctly regardless of the warning.
Warnings in **①log.blockMesh, ②log.SHM, ③log.SHM1, ④log.setAlphaField, ⑤log.decomposePar**. 

But it doesn't seem to work well, there are still some errors as below:
**errors** in ①log.interFlow of case03_cavityWetting, **errors starting from line 1830 in log.interFlow**.
(case/03_cavityWetting whitout any editing, I cloned it and ran it, oh, I changed the number of cores, I don't think it matters)

(Again, I have checked the installation steps one by one, OpenFOAM-v2212 → TwoPhaseFlow2206 → sepMultiphaseFoam, all installations and tests on a clean virtual machine Ubuntu 2004.  Also tested on WSL2 using OpenFOAM-v2112 + TwoPhaseFlow-of2112)

> before installation TwoPhaseFlow2206, I have ensured that OpenFOAM-v2212 is fully installed and running correctly,
> before installation sepMultiphaseFoam, I have ensured that TwoPhaseFlow2206 is fully installed and running correctly,
> before compile sepMultiphaseFoam, the TwoPhaseFlow2206 library path and version adjusted at Make/option file's line 10 yet.

The compilation output and log files are  attached to this zipfile.
[03_cavityWetting.zip](https://github.com/boschresearch/sepMultiphaseFoam/files/12909046/03_cavityWetting.zip)

 the wisp correction has not been included lately, thanks. i will note it in the further coding and simulation investigation.

By the way, I am following your ResearchGate, and look forward to receiving further updates on your research.

Best regards & thanks
Na

**Comment by MontelukastNa** [comment]
> Hello Luise-Nagel, I appreciate your kind reply, thank you very much.❤
> 
> I checked the version of my OpenFOAM and TwoPhaseFlow again, it is OpenFOAM-v2212 + TwoPhaseFlow2206. Before ./Allwmake, the ~/OpenFOAM-v2212/etc/bashrc was sourced correctly.
> 
> As you mentioned, the libraries are only necessary for the solver, the simulations should run correctly regardless of the warning. Warnings in **①log.blockMesh, ②log.SHM, ③log.SHM1, ④log.setAlphaField, ⑤log.decomposePar**.
> 
> But it doesn't seem to work well, there are still some errors as below: **errors** in ①log.interFlow of case03_cavityWetting, **errors starting from line 1830 in log.interFlow**. (case/03_cavityWetting whitout any editing, I cloned it and ran it, oh, I changed the number of cores, I don't think it matters)
> 
> (Again, I have checked the installation steps one by one, OpenFOAM-v2212 → TwoPhaseFlow2206 → sepMultiphaseFoam, all installations and tests on a clean virtual machine Ubuntu 2004. Also tested on WSL2 using OpenFOAM-v2112 + TwoPhaseFlow-of2112)
> 
> > before installation TwoPhaseFlow2206, I have ensured that OpenFOAM-v2212 is fully installed and running correctly,
> > before installation sepMultiphaseFoam, I have ensured that TwoPhaseFlow2206 is fully installed and running correctly,
> > before compile sepMultiphaseFoam, the TwoPhaseFlow2206 library path and version adjusted at Make/option file's line 10 yet.
> 
> The compilation output and log files are attached to this zipfile. [03_cavityWetting.zip](https://github.com/boschresearch/sepMultiphaseFoam/files/12909046/03_cavityWetting.zip)
> 
> the wisp correction has not been included lately, thanks. i will note it in the further coding and simulation investigation.
> 
> By the way, I am following your ResearchGate, and look forward to receiving further updates on your research.
> 
> Best regards & thanks Na

Hello Luise-Nagel,
I appreciate your kind reply, thank you very much.❤

I checked the version of my OpenFOAM and TwoPhaseFlow again, it is OpenFOAM-v2212 + TwoPhaseFlow2206.
Before ./Allwmake, the ~/OpenFOAM-v2212/etc/bashrc was sourced correctly.

As you mentioned, the libraries are only necessary for the solver, the simulations should run correctly regardless of the warning.
Warnings in ①log.blockMesh, ②log.SHM, ③log.SHM1, ④log.setAlphaField, ⑤log.decomposePar.

But it doesn't seem to work well, there are still some errors as below:
errors in ①log.interFlow of case03_cavityWetting, errors starting from line 1830 in log.interFlow.
(case/03_cavityWetting whitout any editing, I cloned it and ran it, oh, I changed the number of cores, I don't think it matters)

(Again, I have checked the installation steps one by one, OpenFOAM-v2212 → TwoPhaseFlow2206 → sepMultiphaseFoam, all installations and tests on a clean virtual machine Ubuntu 2004. Also tested on WSL2 using OpenFOAM-v2112 + TwoPhaseFlow-of2112)

before installation TwoPhaseFlow2206, I have ensured that OpenFOAM-v2212 is fully installed and running correctly,
before installation sepMultiphaseFoam, I have ensured that TwoPhaseFlow2206 is fully installed and running correctly,
before compile sepMultiphaseFoam, the TwoPhaseFlow2206 library path and version adjusted at Make/option file's line 10 yet.

The compilation output and log files are attached to this zipfile.
[03_cavityWetting.zip](https://github.com/boschresearch/sepMultiphaseFoam/files/12909046/03_cavityWetting.zip)

the wisp correction has not been included lately, thanks. i will note it in the further coding and simulation investigation.

By the way, I am following your ResearchGate, and look forward to receiving further updates on your research.

Best regards & thanks
Na

**Comment by MontelukastNa** [comment]
> Hi Na,
> 
> thank you for your interest in our work!
> 
> The warning is definitely not negligible, the libraries seem to be compiled unsuccessfully or in an incompatible version.
> 
> From your description it seems like you're not doing anything wrong. Surely you sourced the correct OpenFOAM version before running the cases? Could you please also attach the compilation output? I'll investigate further and try to find the error.
> 
> _* EDIT- could you also specify in which application the error occurs? Probably it occurs when you are running blockMesh? Do the other applications, mostly interIsoFoam or interFlow, also produce this warning? If it only occurs in blockMesh and setAlphaField, then it might be neglegible after all.... but it's still weird._
> 
> Thank you & best regards Luise

Hello Luise-Nagel,
I appreciate your kind reply, thank you very much.❤

I checked the version of my OpenFOAM and TwoPhaseFlow again, it is OpenFOAM-v2212 + TwoPhaseFlow2206.
Before ./Allwmake, the ~/OpenFOAM-v2212/etc/bashrc was sourced correctly.

As you mentioned, the libraries are only necessary for the solver, the simulations should run correctly regardless of the warning.
Warnings in ①log.blockMesh, ②log.SHM, ③log.SHM1, ④log.setAlphaField, ⑤log.decomposePar.

But it doesn't seem to work well, there are still some errors as below:
errors in ①log.interFlow of case03_cavityWetting, errors starting from line 1830 in log.interFlow.
(case/03_cavityWetting whitout any editing, I cloned it and ran it, oh, I changed the number of cores, I don't think it matters)

(Again, I have checked the installation steps one by one, OpenFOAM-v2212 → TwoPhaseFlow2206 → sepMultiphaseFoam, all installations and tests on a clean virtual machine Ubuntu 2004. Also tested on WSL2 using OpenFOAM-v2112 + TwoPhaseFlow-of2112)

before installation TwoPhaseFlow2206, I have ensured that OpenFOAM-v2212 is fully installed and running correctly,
before installation sepMultiphaseFoam, I have ensured that TwoPhaseFlow2206 is fully installed and running correctly,
before compile sepMultiphaseFoam, the TwoPhaseFlow2206 library path and version adjusted at Make/option file's line 10 yet.

The compilation output and log files are attached to this zipfile.
[03_cavityWetting.zip](https://github.com/boschresearch/sepMultiphaseFoam/files/12909046/03_cavityWetting.zip)

the wisp correction has not been included lately, thanks. i will note it in the further coding and simulation investigation.

By the way, I am following your ResearchGate, and look forward to receiving further updates on your research.

Best regards & thanks
Na

**Comment by Luise-Nagel** [comment]
Hello Na,

I found the solution to your initial issue. I added pull request #4  . 
The solution is: add two additional libraries to load in the controlDict.

instead of 
`libs            ( "libfvOptionArtificialViscousInterfaceForce.so" );
`

we instead use
```
libs            (   "libVoF.so"
                    "libfvOptions.so"
                    "libfvOptionArtificialViscousInterfaceForce.so" );
```

This should solve the warning. For the second issue you mentioned, I will investigate further and open a new issue.

Thank you and best regards!
Luise

**Comment by CFDexplorer** [comment]
Bug fixed and code updated

**Comment by Luise-Nagel** [comment]
Dear @MontelukastNa, 

A final comment on the second warning you mentioned - To my knowledge, this is a warning occurring in all interFlow simulations, even without my modifications, so it is not for me to solve. Since it is only a warning you should be able to ignore it, I tested your case and the simulation runs until the end. 

Best regards
Luise
